create table if not exists collection_box_entity (
    id bigint generated by default as identity,
    event_id bigint,
    primary key (id)
);

create table currency_balance (
    collection_box_entity_id bigint not null,
    currencies numeric(38,2) not null,
    currency varchar(3) not null,
    primary key (collection_box_entity_id, currency)
);
create table event_entity (
    id bigint generated by default as identity,
    balance numeric(38,2) not null,
    currency varchar(3) not null,
    name varchar(255) not null,
    primary key (id)
);
alter table if exists collection_box_entity add constraint FKrie8aswsc8nn1s40er39qshhc foreign key (event_id) references event_entity;
alter table if exists currency_balance add constraint FK7sk11tp3ceivbfio90slhnpe1 foreign key (collection_box_entity_id) references collection_box_entity;